# Generated by Django 3.2.4 on 2021-08-11 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo.', max_length=150, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, help_text='Digite seu e-mail.', max_length=200, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, help_text='Digite seu número de CPF (opcional)', max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
