# Generated by Django 3.2.4 on 2021-09-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
    ]
