# Generated by Django 3.2.4 on 2021-09-14 14:01

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=stdimage.models.StdImageField(upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
