# Generated by Django 3.2.4 on 2021-09-14 14:18

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20210914_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=stdimage.models.StdImageField(upload_to='imagens', verbose_name='Foto de Perfil'),
        ),
    ]
